import { Metadata } from "next";

/**
 * If the title attribute is an object, it support three keys
 * {
 *    absolute,
 *    default,
 *    template
 * }
 * 
 * title.default property is useful when we want to provide a fallback title for
 * child route segments, they don't explicitly specify a title.
 * 
 * To create a Dynamic titles by adding a prefix or a suffix, we can use title.template property. It is applied to child route segments and not the segment in which it is defined.
 * 
 * If we want to provide a title that completly ignores title.template set in the parent
 * segement, we can use title.absolute property.
 * 
 */
export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "NextJS Tutorial wooo",
    template: "%s | DynamicTitle"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
        <p>Header</p>
      </header>
      <body>{children}</body>
      <footer style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
        <p>Footer</p>
      </footer>
    </html>
  )
}
